openapi: 3.1.0
info:
  title: Absence App
  version: 1.0.0
  description: Absence App API
servers:
  - url: http://localhost:8000/api
    description: Local server
tags:
  - name: Auth
    description: Authentication management
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT